EasyImagery/EasyImagery/Models/Clinic.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Bogus.DataSets;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EasyImagery.Models;

public class Clinic
{
    public int Id { get; set; }

    [Required]
    [MaxLength(100)]
    public string? Name { get; set; }

    [MaxLength(500)]
    public string? Description { get; set; }

    [Display(Name = "Manager Id")]
    public string? ManagerId { get; set; }

    public ApplicationUser? Manager { get; set; }

    [Required]
    [MaxLength(200)]
    public string? Address { get; set; }

    public ICollection<ApplicationUser>? Physicians { get; set; }
}

EasyImagery/EasyImagery/Controllers/ClinicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EasyImagery.Data;
using EasyImagery.Models;

namespace EasyImagery.Controllers
{
    public class ClinicsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClinicsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clinics
        public async Task<IActionResult> Index()
        {
            return _context.Clinic != null ?
                        View(await _context.Clinic.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Clinic'  is null.");
        }

        // GET: Clinics/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Clinic == null)
            {
                return NotFound();
            }

            var clinic = await _context.Clinic
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clinic == null)
            {
                return NotFound();
            }

            return View(clinic);
        }

        // GET: Clinics/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clinics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ManagerId,Address")] Clinic clinic)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clinic);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clinic);
        }

        // GET: Clinics/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clinic == null)
            {
                return NotFound();
            }

            var clinic = await _context.Clinic.FindAsync(id);
            if (clinic == null)
            {
                return NotFound();
            }
            return View(clinic);
        }

        // POST: Clinics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ManagerId,Address")] Clinic clinic)
        {
            if (id != clinic.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clinic);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClinicExists(clinic.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clinic);
        }

        // GET: Clinics/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clinic == null)
            {
                return NotFound();
            }

            var clinic = await _context.Clinic
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clinic == null)
            {
                return NotFound();
            }

            return View(clinic);
        }

        // POST: Clinics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clinic == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Clinic'  is null.");
            }
            var clinic = await _context.Clinic.FindAsync(id);
            if (clinic != null)
            {
                _context.Clinic.Remove(clinic);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClinicExists(int id)
        {
            return (_context.Clinic?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

EasyImagery/EasyImagery/Controllers/TimeslotsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EasyImagery.Data;
using EasyImagery.Models;
using EasyImagery.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using CsvHelper;
using OfficeOpenXml;
using System.Globalization;

namespace EasyImagery
{
    [Authorize]
    public class TimeslotsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly EmailSender _emailSender;
        private readonly UserManager<ApplicationUser> _userManager;

        public TimeslotsController(ApplicationDbContext context, EmailSender emailSender, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _emailSender = emailSender;
            _userManager = userManager;
        }

        // GET: Timeslots
        public async Task<IActionResult> Index(string? pid)
        {
            string physicianId = "1";
            if (pid != null)
            {
                physicianId = pid;
            }
            var applicationDbContext = _context.Timeslot.Where(t => t.PhysicianId == pid).Include(t => t.Physician);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> TimeslotsByClinic(int clinicId, int pageNumber = 1, string searchTerm = null, string sortOrder = "asc")
        {
            const int PageSize = 10;

            var physicianIds = await _context.Physician
                .Where(p => p.PhysicianClinicId == clinicId)
                .Select(p => p.Id)
                .ToListAsync();

            var query = _context.Timeslot
                .Where(t => physicianIds.Contains(t.PhysicianId));

            if (!string.IsNullOrEmpty(searchTerm))
            {
                query = query.Where(t => t.Description.Contains(searchTerm));
            }

            switch (sortOrder.ToLower())
            {
                case "desc":
                    query = query.OrderByDescending(t => t.StartDate);
                    break;
                default:
                    query = query.OrderBy(t => t.StartDate);
                    break;
            }

            var timeslots = await query
                .Skip((pageNumber - 1) * PageSize)
                .Take(PageSize)
                .ToListAsync();

            var totalItems = await query.CountAsync();

            var model = new TimeslotViewModel
            {
                Timeslots = timeslots,
                PageNumber = pageNumber,
                TotalPages = (int)Math.Ceiling(totalItems / (double)PageSize),
                SearchTerm = searchTerm,
                ClinicId = clinicId,
                SortOrder = sortOrder
            };

            return View(model);
        }

        // GET: Timeslots/MyTimeslots
        [Authorize(Roles = "Physician")] // Assuming physicians have a role named "Physician"
        public async Task<IActionResult> MyTimeslots()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = "User not authorized." });
            }

            var timeslots = await _context.Timeslot
                                         .Where(t => t.PhysicianId == user.Id)
                                         .Include(t => t.Patient)
                                         .ToListAsync();
            return View(timeslots);
        }

        // GET: Timeslots/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Timeslot == null)
            {
                return NotFound();
            }

            var timeslot = await _context.Timeslot
                .Include(t => t.Physician)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (timeslot == null)
            {
                return NotFound();
            }

            return View(timeslot);
        }

        public async Task<IActionResult> BookTimeslot(long timeslotId)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = "User not authorized." });
            }

            var existingBooking = await _context.Timeslot.FirstOrDefaultAsync(t => t.PatientId == user.Id);
            if (existingBooking != null)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = "You've already booked an appointment. You can only book one timeslot at a time." });
            }

            var timeslot = await _context.Timeslot.FindAsync(timeslotId);
            if (timeslot == null)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = "Timeslot not found." });
            }
            if (timeslot.PatientId != null)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = "This timeslot is already booked by another user." });
            }

            timeslot.PatientId = user.Id;
            _context.Timeslot.Update(timeslot);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { pid = timeslot.PhysicianId });
        }

        // GET: Timeslots/Create
        public IActionResult Create(string physicianId)
        {
            ViewData["PhysicianId"] = physicianId != null? physicianId : new SelectList(_context.Physician, "Id", "Id");
            return View();
        }

        // POST: Timeslots/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,StartDate,EndDate,PhysicianId,PatientId,Rating,ImageData")] Timeslot timeslot, IFormFile Image)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.Length > 0)
                {
                    using var memoryStream = new MemoryStream();
                    await Image.CopyToAsync(memoryStream);
                    timeslot.ImageData = memoryStream.ToArray();
                }
                _context.Add(timeslot);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PhysicianId"] = new SelectList(_context.Physician, "Id", "Id", timeslot.PhysicianId);
            return View(timeslot);
        }

        // GET: Timeslots/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Timeslot == null)
            {
                return NotFound();
            }

            var timeslot = await _context.Timeslot.FindAsync(id);
            if (timeslot == null)
            {
                return NotFound();
            }
            ViewData["PhysicianId"] = new SelectList(_context.Physician, "Id", "Id", timeslot.PhysicianId);
            return View(timeslot);
        }

        // POST: Timeslots/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Description,StartDate,EndDate,PhysicianId,PatientId,Rating,ImageData")] Timeslot timeslot, IFormFile Image)
        {
            if (id != timeslot.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (Image != null && Image.Length > 0)
                {
                    using var memoryStream = new MemoryStream();
                    await Image.CopyToAsync(memoryStream);
                    timeslot.ImageData = memoryStream.ToArray();
                }
                try
                {
                    _context.Update(timeslot);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimeslotExists(timeslot.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PhysicianId"] = new SelectList(_context.Physician, "Id", "Id", timeslot.PhysicianId);
            return View(timeslot);
        }

        // GET: Timeslots/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Timeslot == null)
            {
                return NotFound();
            }

            var timeslot = await _context.Timeslot
                .Include(t => t.Physician)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (timeslot == null)
            {
                return NotFound();
            }

            return View(timeslot);
        }

        // POST: Timeslots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Timeslot == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Timeslot'  is null.");
            }
            var timeslot = await _context.Timeslot.FindAsync(id);
            if (timeslot != null)
            {
                _context.Timeslot.Remove(timeslot);
            }
            

EasyImagery/EasyImagery/Views/Clinics/Create.cshtml
@model EasyImagery.Models.Clinic

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Clinic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManagerId" class="control-label"></label>
                <input asp-for="ManagerId" class="form-control" />
                <span asp-validation-for="ManagerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EasyImagery/EasyImagery/Views/Clinics/Delete.cshtml
@model EasyImagery.Models.Clinic

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Clinic</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManagerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManagerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EasyImagery/EasyImagery/Views/Clinics/Details.cshtml
@model EasyImagery.Models.Clinic

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Clinic</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManagerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManagerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EasyImagery/EasyImagery/Views/Clinics/Edit.cshtml
@model EasyImagery.Models.Clinic

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Clinic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManagerId" class="control-label"></label>
                <input asp-for="ManagerId" class="form-control" />
                <span asp-validation-for="ManagerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EasyImagery/EasyImagery/Views/Clinics/Index.cshtml
@model IEnumerable<EasyImagery.Models.Clinic>
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Clinic";
    var isAdmin = false;
    if (User != null)
    {
        var user = await UserManager.GetUserAsync(User);
        if (user != null)
        {
            isAdmin = await UserManager.IsInRoleAsync(user, "Admin");
        }
    }
}

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAg8EX9QnWyKpINCIZQn9xuvcKXrf4dsZs&callback=initMap"></script>
<script>
    var map;
    var clinics = [
        { id: 1, lat: -37.815336, lng: -215.031205, title: 'Clinic 1' },
        { id: 2, lat: -37.818048, lng: -215.045291, title: 'Clinic 2' },
    ];
    function initMap() {
        var centerLocation = { lat: -37.816217, lng: -215.040309 };

        map = new google.maps.Map(document.getElementById('map'), {
            zoom: 14,
            center: centerLocation
        });

        clinics.forEach(function (clinic) {
            var marker = new google.maps.Marker({
                position: clinic,
                map: map,
                title: clinic.title
            });

            marker.addListener('click', function () {
                window.open('https://www.google.com/maps/dir/?api=1&destination=' + clinic.lat + ',' + clinic.lng, '_blank');
            });
        });
    }

    function focusOnClinic(clinicId) {
        var clinic = clinics.find(c => c.id == clinicId);
        if (clinic) {
            map.setCenter({ lat: clinic.lat, lng: clinic.lng });
            map.setZoom(16);
        }
    }

    document.addEventListener('DOMContentLoaded', function () {
        var mapButtons = document.querySelectorAll('.btn-view-on-map');
        mapButtons.forEach(function (button) {
            button.addEventListener('click', function () {
                var clinicId = button.getAttribute('data-clinic-index');
                focusOnClinic(clinicId);
            });
        });
    });
</script>

<h1>Clinic</h1>

<div class="my-4" id="map" style="height: 400px; width: 100%;"></div>

@if (isAdmin)
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
                <td>
                    <button class="btn btn-secondary btn-view-on-map" data-clinic-index="@item.Id">View on Map</button>
                </td>
            <td>
                    <a class="btn btn-primary" asp-controller="Timeslots" asp-action="TimeslotsByClinic" asp-route-clinicid="@item.Id">All Timeslots</a>
            </td>
            <td>
                @if (isAdmin)
                {
                    <span>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </span>
                } else
                {
                    <a class="btn btn-primary" asp-controller="Physician" asp-action="Index" asp-route-itemid="@item.Id">See Physicians</a>
                }
            </td>
        </tr>
    }
    </tbody>
</table>